package view;

import controller.InterviewPlayer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Menu {
    private JFrame frame;
    private JPanel panel;
    private JButton roboterlisteButton;
    private JButton interviewlisteButton;
    private JButton interviewPlayerButton;
    private JButton interviewEditorButton;
    private JButton hilfeButton;


    public Menu() {

        roboterlisteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setVisible(false);
                new Robotlist(frame);
            }
        });
        interviewPlayerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               // frame.setVisible(false);

                new InterviewSelection(frame);


            }
        });

        frame = new JFrame("Nao2Nao");
        frame.setPreferredSize(new Dimension(250, 400));
        frame.setContentPane(panel);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.pack();
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        roboterlisteButton = new JButton();
        roboterlisteButton.setMaximumSize(new Dimension(99, 35));
        roboterlisteButton.setPreferredSize(new Dimension(99, 35));
        roboterlisteButton.setText("Roboterliste");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(roboterlisteButton, gbc);
        interviewlisteButton = new JButton();
        interviewlisteButton.setMaximumSize(new Dimension(105, 35));
        interviewlisteButton.setPreferredSize(new Dimension(105, 35));
        interviewlisteButton.setText("Interviewliste");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(interviewlisteButton, gbc);
        interviewPlayerButton = new JButton();
        interviewPlayerButton.setPreferredSize(new Dimension(116, 35));
        interviewPlayerButton.setText("InterviewPlayer");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(interviewPlayerButton, gbc);
        interviewEditorButton = new JButton();
        interviewEditorButton.setPreferredSize(new Dimension(115, 35));
        interviewEditorButton.setText("InterviewEditor");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(interviewEditorButton, gbc);
        hilfeButton = new JButton();
        hilfeButton.setPreferredSize(new Dimension(61, 35));
        hilfeButton.setText("Hilfe");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(hilfeButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}