package view;


import model.interview.Interview;
import model.robot.Robot;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class RobotSelection extends JFrame {
    private JPanel panel;
    private JComboBox[] comboxes;
    private JLabel[] lables;
    private JButton bestaetigenButton;


    public RobotSelection(JFrame mainFrame, Interview interview) {
        setContentPane(panel);
        setPreferredSize(new Dimension(200, 300));
        setResizable(false);

        //Mittige Ausrichtugn
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        int dx = (ge.getCenterPoint().x - getSize().width / 2);
        int dy = (ge.getCenterPoint().y - getSize().height / 2);
        setLocation(dx, dy);

        comboxes = new JComboBox[interview.getAnzahlTeilnehmer()];
        lables = new JLabel[interview.getAnzahlTeilnehmer()];

        for (JLabel label : lables) {
            label = new JLabel("Name");
            panel.add(label);
        }

        for (JComboBox cB : comboxes) {
            cB = new JComboBox();
            cB.setSize(new Dimension(100, 50));
            DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
            cB.setModel(defaultComboBoxModel1);
            for (Robot r : Robot.getRobotList()) {
                System.out.println(r.getName());
                cB.addItem(r);
            }
            panel.add(BorderLayout.EAST, cB);
        }


        bestaetigenButton = new JButton("Bestätigen");
        panel.add(BorderLayout.SOUTH, bestaetigenButton);
        setResizable(false);
        setVisible(true);
        repaint();
        pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}

